# detect-secrets configuration
# https://github.com/Yelp/detect-secrets

[tool.detect-secrets]
# Version compatibility
version = "1.5.0"

# Baseline file location
baseline = ".secrets.baseline"

# Exclude patterns for files
exclude_files = [
  ".*\\.(lock|sum)$",
  "^node_modules/",
  "^\\.pnpm-store/",
  "^\\.npm-global/",
  "^\\.cargo/",
  "^\\.cache/",
  "^target/",
  "^dist/",
  "^build/",
  "^coverage/",
  "^\\.reports/",
  # Child repositories
  "^actions/",
  "^containers/",
  "^dot-github/",
  "^style-system/",
]

# Exclude patterns for lines
exclude_lines = [
  ".*pragma: allowlist.*",
  ".*secretsignore.*",
]

# Plugin configuration
[tool.detect-secrets.plugins]
# High entropy string detection
base64_limit = 4.5
hex_limit = 3.0

# Disable plugins that generate too many false positives
disable_plugins = [  ]

# Filter configuration
[tool.detect-secrets.filters]
# Enable all default heuristic filters
enable_filters = [
  "detect_secrets.filters.heuristic.is_indirect_reference",
  "detect_secrets.filters.heuristic.is_likely_id_string",
  "detect_secrets.filters.heuristic.is_lock_file",
  "detect_secrets.filters.heuristic.is_not_alphanumeric_string",
  "detect_secrets.filters.heuristic.is_potential_uuid",
  "detect_secrets.filters.heuristic.is_prefixed_with_dollar_sign",
  "detect_secrets.filters.heuristic.is_sequential_string",
  "detect_secrets.filters.heuristic.is_swagger_file",
  "detect_secrets.filters.heuristic.is_templated_secret",
]
