# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

version: 2

run:
  timeout: 5m
  skip-dirs:
    - actions
    - containers
    - dot-github
    - style-system
    - vendor
    - .npm-global
    - node_modules

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosec
    - ineffassign
    - unconvert
    - dupl
    - misspell
    - unparam
    - nakedret
    - gocyclo
    - gocognit

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  misspell:
    locale: US
