# Markdownlint CLI2 configuration
# This file configures markdownlint-cli2 behavior (not the rules themselves)

# Use existing config for rules
config: .markdownlint.yaml

# Default glob patterns to process
globs: ["**/*.md", "**/*.markdown"]

# Ignores - must be an array of globs
ignores:
  [
    "actions/**",
    "containers/**",
    "dot-github/**",
    "style-system/**",
    "node_modules/**",
    ".npm-global/**",
    "vendor/**",
    ".reports/**",
    "coverage/**",
    "docs/generated/**",
    ".cache/**",
    "tmp/**",
    ".tmp/**",
    "CHANGELOG.md",
    "LICENSE.md",
    ".git/**",
  ]

# Disable fixing - pre-commit hooks must be read-only
fix: false
