# Lychee link checker configuration
# https://github.com/lycheeverse/lychee

# Maximum number of concurrent requests
max_concurrency = 10

# User agent string
user_agent = "Mozilla/5.0 (compatible; BrainCraft.io/1.0; +https://github.com/braincraftio)"

# Request timeout in seconds
timeout = 20

# Maximum number of retries
max_retries = 2

# Accept these status codes
accept = [200, 201, 202, 203, 204, 206, 301, 302, 304, 401, 403]

# Exclude patterns
exclude = [
  # Localhost and local network
  "^https?://localhost",
  "^https?://127\\.0\\.0\\.1",
  "^https?://192\\.168\\.",
  "^https?://10\\.",

  # Common development URLs
  "^https?://example\\.com",
  "^https?://test\\.com",

  # GitHub edit/new links
  "^https://github\\.com/.*/edit/",
  "^https://github\\.com/.*/new/",

  # Anchors in markdown (handled separately)
  "^#",

  # Private GitHub repos (will 404 without auth)
  "^https://github\\.com/braincraftio/.*/(pull|issues|actions)",
]

# Check anchors
include_anchor = true

# Check fragments
include_fragments = true

# Skip missing files when offline
skip_missing = true

# Cache results for 1 hour
cache = true

# Exclude private IPs
exclude_private = true

# Exclude mail addresses
exclude_mail = true

# Exclude paths
exclude_path = [
  ".npm-global",
  "node_modules",
  ".git",
  ".mise",
  ".cargo",
  ".cache",
  "target",
  "dist",
  "build",
  "tmp"
]
