# Taplo configuration for BrainCraft.io workspace
# https://taplo.tamasfe.dev/configuration/

# Exclude child repositories and common directories
exclude = [
  "actions/**/*.toml",
  "containers/**/*.toml",
  "dot-github/**/*.toml",
  "style-system/**/*.toml",
  "target/**/*.toml",
  ".cargo/**/*.toml",
  "node_modules/**/*.toml",
  ".npm-global/**/*.toml",
  ".git/**/*.toml",
  ".cache/**/*.toml",
  "tmp/**/*.toml",
  "vendor/**/*.toml",
]

[formatting]
# Don't align entries - keeps diffs cleaner
align_entries = false

# Keep trailing commas in arrays for cleaner diffs
array_trailing_comma = true

# Don't auto-expand arrays
array_auto_expand = false

# Don't auto-collapse arrays
array_auto_collapse = false

# Keep arrays compact
compact_arrays = false

# Keep inline tables readable
compact_inline_tables = false

# Don't indent tables - keeps structure flat
indent_tables = false

# Don't indent entries under tables
indent_entries = false

# Don't reorder keys - preserve original order
reorder_keys = false

# Allow one blank line maximum
allowed_blank_lines = 1

# Use 2 spaces for indentation
indent_string = "  "

# Ensure trailing newline
trailing_newline = true

# Use LF line endings
crlf = false

# Schema validation
[schema]
enabled = true
# The schema catalog URL will be automatically used from defaults
